builds:
- env:
    - CGO_ENABLED=0
  binary: cloud-platform
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=cloud-platform
changelog:
  sort: asc
  filters:
    exclude:
    - Merge pull request
    - Merge branch
    - go mod tidy
