// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Applier is an autogenerated mock type for the Applier type
type Applier struct {
	mock.Mock
}

// Initialize provides a mock function with given fields:
func (_m *Applier) Initialize() {
	_m.Called()
}

// KubectlApply provides a mock function with given fields: directory
func (_m *Applier) KubectlApply(directory string) (string, error) {
	ret := _m.Called(directory)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(directory)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(directory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TerraformDestroy provides a mock function with given fields: directory
func (_m *Applier) TerraformDestroy(directory string) error {
	ret := _m.Called(directory)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(directory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TerraformInitAndApply provides a mock function with given fields: namespace, directory
func (_m *Applier) TerraformInitAndApply(namespace string, directory string) (string, error) {
	ret := _m.Called(namespace, directory)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(namespace, directory)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(namespace, directory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewApplier interface {
	mock.TestingT
	Cleanup(func())
}

// NewApplier creates a new instance of Applier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewApplier(t mockConstructorTestingTNewApplier) *Applier {
	mock := &Applier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
