name: Build docs

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.23.x"

      - name: Install Go
        run: go install
        working-directory: ./

      - name: Recreate docs directory
        run: rm -r doc/ && mkdir -p doc

      - name: Generate docs
        run: go run main.go generate-docs --skip-version-check

      - name: Commit generated docs if on main
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add doc/

          # Exit cleanly if no changes
          if git diff --cached --quiet; then
            echo "No documentation changes to commit"
            exit 0
          fi

          git commit -m "Auto Commit Docs"
          git push
