name: Test Go code

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  go-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Install Go on the VM running the action.
      - uses: actions/setup-go@v5
        with:
          go-version: "1.19.x"

      # Run tests with nice formatting. Save the original log in /tmp/gotest.log
      - name: Run tests
        run: |
          set -euo pipefail
          go test --tags integration -json -race -covermode=atomic -coverprofile=coverage.out -v ./... 2>&1 | tee ~/gotest.log

      # Upload the original go test log as anhaveyoudebuggedit/gotestfmt-action@v2haveyoudebuggedit/gotestfmt-action@v2 artifact for later review.
      - name: Upload test log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-log
          path: ~/gotest.log
          if-no-files-found: error

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
